# Monokai-pro-spectrum for Kitty
# Based on https://www.monokai.pro/

include ../theme/monokai.conf

dim_opacity 0.5
inactive_text_alpha 0.5
active_border_color #19181a
draw_minimal_borders yes
window_padding_width 14
window_margin_width 0
macos_titlebar_color background

tab_fade 0.1 0.2 0.8 1
tab_bar_margin_width 1.0

font_family      SauceCodePro Nerd Font Mono
bold_font        SauceCodePro Nerd Font Mono
italic_font      SauceCodePro Nerd Font Mono
bold_italic_font SauceCodePro Nerd Font Mono
# font_size 12.0

background_opacity 0.85
dynamic_background_opacity yes

map cntrl+shift+enter no_op
