# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 10
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 0.97
    inactive_opacity = 0.90

    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(00000055)
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        ignore_opacity = true
        xray = false
        popups = true
        vibrancy = 0.1696
    }
}
